# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 01:28
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_way', models.TextField(verbose_name='json_way')),
                ('schedule', models.CharField(max_length=7, verbose_name='schedule')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('rout_sumary', models.TextField(blank=True, null=True, verbose_name='rout_sumary')),
                ('rout_duration', models.CharField(max_length=50, null=True, verbose_name='rout_duration')),
                ('rout_distance', models.CharField(max_length=50, null=True, verbose_name='rout_duration')),
                ('rout_start_lat', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('rout_start_lng', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('start_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('rout_end_lat', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('rout_end_lng', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('end_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('rout_start_address', models.TextField(blank=True, null=True, verbose_name='rout_start_address')),
                ('rout_end_address', models.TextField(blank=True, null=True, verbose_name='rout_end_address')),
                ('rout_overviewpolilyne', models.TextField(blank=True, null=True, verbose_name='rout_overviewpolilyne')),
                ('rout_bound_sw_lat', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('rout_bound_sw_lng', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('rout_bound_ne_lat', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('rout_bound_ne_lng', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Driver', to=settings.AUTH_USER_MODEL, verbose_name='Usuario_Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leg', to='pooling.Driver', verbose_name='driver')),
            ],
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lat', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('start_lng', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('start_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('end_lat', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('end_lnt', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('end_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('schedule', models.CharField(max_length=7, null=True, verbose_name='schedule')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Seeker', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Seeker')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lat', models.DecimalField(decimal_places=10, max_digits=19)),
                ('start_lng', models.DecimalField(decimal_places=10, max_digits=19)),
                ('start_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('end_lat', models.DecimalField(decimal_places=10, max_digits=19)),
                ('end_lng', models.DecimalField(decimal_places=10, max_digits=19)),
                ('end_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('polyline', models.TextField(blank=True, verbose_name='polyline')),
                ('duration', models.CharField(max_length=50, null=True, verbose_name='rout_duration')),
                ('html_instruction', models.TextField(blank=True, verbose_name='html_instruction')),
                ('distance', models.CharField(max_length=50, null=True, verbose_name='rout_duration')),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step', to='pooling.Leg', verbose_name='leg')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('start_distance', models.FloatField()),
                ('end_distance', models.FloatField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_driver', to='pooling.Driver', verbose_name='driver')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_seeker', to='pooling.Seeker', verbose_name='seeker')),
            ],
        ),
    ]
